from __future__ import annotations

from dataclasses import dataclass
import random
from typing import Dict, Iterable, List, Optional, Tuple


@dataclass(frozen=True)
class Player:
    name: str
    role: str
    finishing: int = 10
    creativity: int = 10
    tackling: int = 10
    stamina: int = 10
    positioning: int = 10
    pace: int = 10


@dataclass(frozen=True)
class Team:
    name: str
    players: List[Player]


@dataclass(frozen=True)
class Tactic:
    mentality: str
    width: int
    pressing: int
    tempo: int


@dataclass(frozen=True)
class MatchContext:
    weather: str
    referee_strictness: int
    home_advantage: float


@dataclass(frozen=True)
class MatchCommand:
    tick: int
    team: str
    tactic: Tactic


@dataclass(frozen=True)
class TeamStats:
    shots: int = 0
    shots_on_target: int = 0
    goals: int = 0
    second_half_pressure: float = 0.0


@dataclass(frozen=True)
class MatchReport:
    scoreline: str
    key_reasons: List[str]
    stat_summary: Dict[str, TeamStats]


@dataclass(frozen=True)
class MatchResult:
    score: Tuple[int, int]
    events: List[str]
    team_stats: Dict[str, TeamStats]
    fatigue: Dict[str, float]
    diagnostics: List[str]
    command_log: List[str]
    report: MatchReport

    @property
    def total_shots(self) -> int:
        return sum(stats.shots for stats in self.team_stats.values())


@dataclass
class _MutableStats:
    shots: int = 0
    shots_on_target: int = 0
    goals: int = 0
    first_half_pressure: float = 0.0
    second_half_pressure: float = 0.0

    def freeze(self) -> TeamStats:
        return TeamStats(
            shots=self.shots,
            shots_on_target=self.shots_on_target,
            goals=self.goals,
            second_half_pressure=round(self.second_half_pressure, 3),
        )


def simulate_match(
    home: Team,
    away: Team,
    home_tactic: Tactic,
    away_tactic: Tactic,
    context: MatchContext,
    *,
    seed: int,
    commands: Optional[List[MatchCommand]] = None,
) -> MatchResult:
    """Deterministic throwaway match simulation for spike 001.

    This is intentionally small and explicit. It is not the real production match
    engine; it exists to validate API shape, deterministic replay, and whether the
    proposed tests capture the behaviours we care about.
    """
    rng = random.Random(seed)
    current_tactics = {home.name: home_tactic, away.name: away_tactic}
    teams = {home.name: home, away.name: away}
    ordered_commands = sorted(commands or [], key=lambda command: command.tick)
    pending_commands = list(ordered_commands)

    stats = {home.name: _MutableStats(), away.name: _MutableStats()}
    fatigue = {home.name: 0.0, away.name: 0.0}
    events: List[str] = []
    diagnostics = _initial_diagnostics(context)
    command_log: List[str] = []

    for tick in range(1, 91):
        while pending_commands and pending_commands[0].tick == tick:
            command = pending_commands.pop(0)
            if command.team not in teams:
                raise ValueError(f"Unknown command team: {command.team}")
            current_tactics[command.team] = command.tactic
            command_log.append(f"{tick}: {command.team} changed to {command.tactic.mentality}")
            events.append(f"{tick}' tactical change: {command.team} switched to {command.tactic.mentality}")

        for attacking_name, defending_name, venue_multiplier in (
            (home.name, away.name, context.home_advantage),
            (away.name, home.name, 1.0),
        ):
            attacking_team = teams[attacking_name]
            defending_team = teams[defending_name]
            tactic = current_tactics[attacking_name]
            opponent_tactic = current_tactics[defending_name]

            pressure = _pressure(attacking_team, defending_team, tactic, opponent_tactic, context, venue_multiplier)
            if tick > 45:
                stats[attacking_name].second_half_pressure += pressure
            else:
                stats[attacking_name].first_half_pressure += pressure

            fatigue[attacking_name] += _fatigue_cost(tactic, context, attacking_team)

            chance_probability = min(0.34, max(0.02, pressure / 100.0))
            if rng.random() < chance_probability:
                stats[attacking_name].shots += 1
                events.append(f"{tick}' {attacking_name} shot generated by {tactic.mentality} pressure")

                shot_quality = _shot_quality(attacking_team, defending_team, tactic, context, fatigue[attacking_name])
                if rng.random() < shot_quality:
                    stats[attacking_name].shots_on_target += 1
                    if rng.random() < _goal_probability(attacking_team, defending_team, tactic, context):
                        stats[attacking_name].goals += 1
                        events.append(f"{tick}' GOAL {attacking_name}")

    frozen_stats = {name: mutable.freeze() for name, mutable in stats.items()}
    rounded_fatigue = {name: round(value, 3) for name, value in fatigue.items()}
    score = (frozen_stats[home.name].goals, frozen_stats[away.name].goals)
    report = _build_report(home, away, home_tactic, away_tactic, context, frozen_stats, score)

    return MatchResult(
        score=score,
        events=events,
        team_stats=frozen_stats,
        fatigue=rounded_fatigue,
        diagnostics=diagnostics,
        command_log=command_log,
        report=report,
    )


def _average(players: Iterable[Player], attribute: str, role: Optional[str] = None) -> float:
    selected = [player for player in players if role is None or player.role == role]
    if not selected:
        selected = list(players)
    return sum(getattr(player, attribute) for player in selected) / len(selected)


def _team_attack(team: Team) -> float:
    return (_average(team.players, "finishing", "ATT") * 0.45 + _average(team.players, "creativity", "MID") * 0.35 + _average(team.players, "pace") * 0.20)


def _team_defense(team: Team) -> float:
    return (_average(team.players, "tackling", "DEF") * 0.45 + _average(team.players, "positioning", "DEF") * 0.35 + _average(team.players, "stamina") * 0.20)


def _mentality_modifier(mentality: str) -> float:
    return {
        "defensive": 0.76,
        "balanced": 1.0,
        "attacking": 1.28,
    }.get(mentality, 1.0)


def _weather_chance_modifier(weather: str) -> float:
    return {
        "normal": 1.0,
        "rain": 0.72,
        "wind": 0.82,
        "hot": 0.90,
    }.get(weather, 1.0)


def _pressure(attacking_team: Team, defending_team: Team, tactic: Tactic, opponent_tactic: Tactic, context: MatchContext, venue_multiplier: float) -> float:
    attack = _team_attack(attacking_team)
    defense = _team_defense(defending_team)
    tempo_bonus = (tactic.tempo - 10) * 0.55
    pressing_bonus = (tactic.pressing - 10) * 0.45
    width_bonus = -abs(tactic.width - 11) * 0.12 + max(0, tactic.width - opponent_tactic.width) * 0.10
    base = 11.5 + (attack - defense) * 0.82 + tempo_bonus + pressing_bonus + width_bonus
    return max(2.0, base * _mentality_modifier(tactic.mentality) * _weather_chance_modifier(context.weather) * venue_multiplier)


def _fatigue_cost(tactic: Tactic, context: MatchContext, team: Team) -> float:
    stamina_resistance = _average(team.players, "stamina") / 24.0
    weather_load = {"normal": 1.0, "rain": 1.33, "wind": 1.12, "hot": 1.45}.get(context.weather, 1.0)
    tactical_load = 0.030 + tactic.pressing * 0.007 + tactic.tempo * 0.005
    if tactic.mentality == "attacking":
        tactical_load += 0.020
    elif tactic.mentality == "defensive":
        tactical_load -= 0.010
    return max(0.015, tactical_load * weather_load - stamina_resistance * 0.01)


def _shot_quality(attacking_team: Team, defending_team: Team, tactic: Tactic, context: MatchContext, accumulated_fatigue: float) -> float:
    attack_edge = _team_attack(attacking_team) - _team_defense(defending_team)
    value = 0.39 + attack_edge * 0.012 + (tactic.tempo - 10) * 0.006 - accumulated_fatigue * 0.002
    if context.weather == "rain":
        value -= 0.10
    return min(0.78, max(0.18, value))


def _goal_probability(attacking_team: Team, defending_team: Team, tactic: Tactic, context: MatchContext) -> float:
    attack_edge = _team_attack(attacking_team) - _team_defense(defending_team)
    value = 0.26 + attack_edge * 0.01
    if tactic.mentality == "attacking":
        value += 0.03
    if context.weather == "rain":
        value -= 0.04
    return min(0.48, max(0.10, value))


def _initial_diagnostics(context: MatchContext) -> List[str]:
    diagnostics = []
    if context.weather == "rain":
        diagnostics.append("rain reduced chance quality")
    if context.referee_strictness >= 15:
        diagnostics.append("strict referee increased foul/card risk")
    if context.home_advantage > 1.0:
        diagnostics.append("home advantage increased home pressure")
    return diagnostics


def _build_report(home: Team, away: Team, home_tactic: Tactic, away_tactic: Tactic, context: MatchContext, stats: Dict[str, TeamStats], score: Tuple[int, int]) -> MatchReport:
    reasons: List[str] = []
    for team, tactic in ((home, home_tactic), (away, away_tactic)):
        if tactic.mentality == "attacking":
            reasons.append(f"{team.name} attacking mentality increased pressure and shot volume")
        elif tactic.mentality == "defensive":
            reasons.append(f"{team.name} defensive mentality reduced risk and shot volume")
    if context.home_advantage > 1.0:
        reasons.append("home advantage increased home pressure")
    if context.weather == "rain":
        reasons.append("rain reduced chance quality and increased fatigue")

    scoreline = f"{home.name} {score[0]}-{score[1]} {away.name}"
    return MatchReport(scoreline=scoreline, key_reasons=reasons, stat_summary=stats)
